### ISSUE TITLE
Add Create and Delete endpoints for all the models

### ISSUE THREAD

**Issue by Rashmil-1999** [Direct4Ag/ag-services#42]
The end goal is to be able to write a script similar to init_db with which we can upload data once the service is hosted.

**Comment by navarroc** [comment]
We should consider adding an API key for simple authentication here. For now, it will mostly be us adding fields so this would prevent unwanted data. Later we can consider something more sophisticated.

**Comment by Rashmil-1999** [comment]
ahh i see, like a specific keyword like being loaded form env that the backend knows and people authorized knows.... doesn't have to be proper API key as well. Ill see if it is not too much effort to put in API key system.
